INPUT_SIZE: 10
HIDDEN_SIZE: 128
NUM_LAYERS: 3
FC_LAYERS_SIZE: 100
LEARNING_RATE: 0.001
TRAIN_DATA: "C:/Users/howar/Documents/UIUC/IE 421/project/group_10_project/20220801_book_updates.csv"
SEQUENCE_LENGTH: 60
PREDICT_EVENTS : 1
BATCH_SIZE: 512
TEST_SPLIT : 0.2
EPOCHS : 100
VAL_INTERVAL : 1